<?php
session_start(); require_once __DIR__.'/conf.php'; header('Content-Type: application/json; charset=utf-8');
$adminUser=getenv('ADMIN_USER')?:'Daler'; $adminPass=getenv('ADMIN_PASSWORD')?:'Lavash'; $action=$_REQUEST['action']??'';
function out($d,$c=200){http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($action==='login'){ $u=trim((string)($_POST['username']??''));$p=(string)($_POST['password']??''); if(hash_equals($adminUser,$u)&&hash_equals($adminPass,$p)){session_regenerate_id(true);$_SESSION['pro_admin']=true;$_SESSION['pro_admin_name']=$u;out(['ok'=>true]);}out(['ok'=>false,'message'=>'Login yoki parol noto‘g‘ri'],401); }
if($action==='logout'){$_SESSION=[];session_destroy();out(['ok'=>true]);} if(empty($_SESSION['pro_admin']))out(['ok'=>false,'message'=>'Unauthorized'],401);
try{
$conn->query("CREATE TABLE IF NOT EXISTS admin_orders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,source_table VARCHAR(128),source_key VARCHAR(191),customer_name VARCHAR(190) NOT NULL DEFAULT '',phone VARCHAR(60) NOT NULL DEFAULT '',address TEXT,note TEXT,amount DECIMAL(12,2) NOT NULL DEFAULT 0,status VARCHAR(40) NOT NULL DEFAULT 'new',courier_id BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY source_ref(source_table,source_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$conn->query("CREATE TABLE IF NOT EXISTS couriers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,phone VARCHAR(60) NOT NULL UNIQUE,status VARCHAR(30) NOT NULL DEFAULT 'offline',last_seen TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$conn->query("CREATE TABLE IF NOT EXISTS customer_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NULL,name VARCHAR(190) NOT NULL,phone VARCHAR(60) NOT NULL UNIQUE,email VARCHAR(190) NULL,address TEXT,password_hash VARCHAR(255) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$conn->query("CREATE TABLE IF NOT EXISTS admin_settings(setting_key VARCHAR(80) PRIMARY KEY,setting_value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$conn->query("INSERT IGNORE INTO admin_settings(setting_key,setting_value) VALUES('store_name','Fast Food'),('phone','+998 99 830 56 03'),('address','Samarqand, Chelak 78 oldi'),('delivery_note','Tez va issiq dastavka'),('delivery_fee','0')");
if($action==='summary'){ $r=[];foreach(['new','confirmed','preparing','delivering','completed','cancelled'] as $s){$q=$conn->query("SELECT COUNT(*) c FROM admin_orders WHERE status='".$conn->real_escape_string($s)."'");$r[$s]=(int)$q->fetch_assoc()['c'];}$r['orders']=(int)$conn->query('SELECT COUNT(*) c FROM admin_orders')->fetch_assoc()['c'];$r['today']=(int)$conn->query("SELECT COUNT(*) c FROM admin_orders WHERE DATE(created_at)=CURDATE()")->fetch_assoc()['c'];$r['revenue']=(float)$conn->query("SELECT COALESCE(SUM(amount),0) v FROM admin_orders WHERE status<>'cancelled'")->fetch_assoc()['v'];$r['online_couriers']=(int)$conn->query("SELECT COUNT(*) c FROM couriers WHERE status='online' AND last_seen>=NOW()-INTERVAL 2 MINUTE")->fetch_assoc()['c'];out(['ok'=>true,'online'=>true,'data'=>$r,'server_time'=>date('c')]); }
if($action==='orders'){ $s=trim((string)($_GET['status']??''));$w=$s!==''?" WHERE o.status='".$conn->real_escape_string($s)."'":'';$q=$conn->query("SELECT o.*,c.name courier_name,c.phone courier_phone FROM admin_orders o LEFT JOIN couriers c ON c.id=o.courier_id$w ORDER BY o.created_at DESC LIMIT 200");$rows=[];while($x=$q->fetch_assoc())$rows[]=$x;out(['ok'=>true,'data'=>$rows,'server_time'=>date('c')]); }
if($action==='status'){ $id=(int)($_POST['id']??0);$s=(string)($_POST['status']??'new');$a=['new','confirmed','preparing','delivering','completed','cancelled'];if(!$id||!in_array($s,$a,true))out(['ok'=>false],422);$st=$conn->prepare('UPDATE admin_orders SET status=? WHERE id=?');$st->bind_param('si',$s,$id);$st->execute();out(['ok'=>true]); }
if($action==='products'){ $q=$conn->query('SELECT * FROM product ORDER BY id DESC');$a=[];while($x=$q->fetch_assoc())$a[]=$x;out(['ok'=>true,'data'=>$a]); }
if($action==='product_save'){ $id=(int)($_POST['id']??0);$title=trim((string)($_POST['p_title']??''));$sub=trim((string)($_POST['p_subtitle']??''));$desc=trim((string)($_POST['p_desc']??''));$price=(float)($_POST['p_prize']??0);$cat=trim((string)($_POST['cat_id']??'cat-20001'));$scat=trim((string)($_POST['scat_id']??'scat-30001'));$image=trim((string)($_POST['p_image']??'dish-1.png'));$status=in_array($_POST['status']??'show',['show','hide'],true)?$_POST['status']:'show';if($title===''||$price<0)out(['ok'=>false,'message'=>'Mahsulot nomi va narxini to‘g‘ri kiriting'],422);if($id){$st=$conn->prepare('UPDATE product SET p_title=?,p_subtitle=?,p_desc=?,p_prize=?,cat_id=?,scat_id=?,p_image=?,status=? WHERE id=?');$st->bind_param('sssissssi',$title,$sub,$desc,$price,$cat,$scat,$image,$status,$id);$st->execute();}else{$pid='p-'.random_int(10000,99999);$uid=$adminUser;$date=date('Y-m-d H:i:s');$st=$conn->prepare("INSERT INTO product(p_id,cat_id,scat_id,u_id,p_title,p_subtitle,p_desc,p_prize,p_image,status,action,date) VALUES(?,?,?,?,?,?,?,?,?,'show','far',?)");$st->bind_param('ssssssdsss',$pid,$cat,$scat,$uid,$title,$sub,$desc,$price,$image,$date);$st->execute();}out(['ok'=>true]); }
if($action==='product_delete'){ $id=(int)($_POST['id']??0);$st=$conn->prepare('DELETE FROM product WHERE id=?');$st->bind_param('i',$id);$st->execute();out(['ok'=>true]); }
if($action==='couriers'){ $q=$conn->query('SELECT id,name,phone,status,last_seen FROM couriers ORDER BY id DESC');$a=[];while($x=$q->fetch_assoc()){$x['online']=$x['status']==='online'&&strtotime($x['last_seen']??'')>=time()-120;$a[]=$x;}out(['ok'=>true,'data'=>$a]); }
if($action==='courier_save'){ $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$phone=preg_replace('/[^0-9+]/','',trim((string)($_POST['phone']??'')));if($name===''||$phone==='')out(['ok'=>false,'message'=>'Ism va telefon kerak'],422);if($id){$st=$conn->prepare('UPDATE couriers SET name=?,phone=? WHERE id=?');$st->bind_param('ssi',$name,$phone,$id);}else{$st=$conn->prepare("INSERT INTO couriers(name,phone,status,last_seen) VALUES(?,?,'offline',NOW())");$st->bind_param('ss',$name,$phone);}$st->execute();out(['ok'=>true]); }
if($action==='courier_delete'){ $id=(int)($_POST['id']??0);$st=$conn->prepare('DELETE FROM couriers WHERE id=?');$st->bind_param('i',$id);$st->execute();out(['ok'=>true]); }
if($action==='assign'){ $order=(int)($_POST['order_id']??0);$courier=(int)($_POST['courier_id']??0);$st=$conn->prepare('UPDATE admin_orders SET courier_id=?,status=IF(status="new","confirmed",status) WHERE id=?');$st->bind_param('ii',$courier,$order);$st->execute();out(['ok'=>true]); }
if($action==='customers'){ $q=$conn->query("SELECT cp.*,COUNT(o.id) orders,COALESCE(SUM(o.amount),0) spent FROM customer_profiles cp LEFT JOIN admin_orders o ON REPLACE(o.phone,' ','')=REPLACE(cp.phone,' ','') GROUP BY cp.id ORDER BY cp.id DESC");$a=[];while($x=$q->fetch_assoc())$a[]=$x;out(['ok'=>true,'data'=>$a]); }
if($action==='settings'){if($_SERVER['REQUEST_METHOD']==='POST'){foreach(['store_name','phone','address','delivery_note','delivery_fee'] as $k)if(isset($_POST[$k])){$v=trim((string)$_POST[$k]);$st=$conn->prepare('INSERT INTO admin_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$st->bind_param('ss',$k,$v);$st->execute();}}$q=$conn->query('SELECT setting_key,setting_value FROM admin_settings');$d=[];while($x=$q->fetch_assoc())$d[$x['setting_key']]=$x['setting_value'];out(['ok'=>true,'data'=>$d]);}
if($action==='health'){out(['ok'=>true,'online'=>true,'db'=>true,'server_time'=>date('c')]);}
out(['ok'=>false,'message'=>'Unknown action'],404);
}catch(Throwable $e){error_log('Admin API: '.$e->getMessage());out(['ok'=>false,'message'=>'Server xatosi'],500);}
?>