<?php
session_start();require_once __DIR__.'/conf.php';header('Content-Type: application/json; charset=utf-8');
function out($x,$c=200){http_response_code($c);echo json_encode($x,JSON_UNESCAPED_UNICODE);exit;}$a=$_REQUEST['action']??'';
try{$conn->query("CREATE TABLE IF NOT EXISTS couriers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,phone VARCHAR(60) NOT NULL UNIQUE,pin_hash VARCHAR(255) NULL,status VARCHAR(30) NOT NULL DEFAULT 'offline',last_seen TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$conn->query("CREATE TABLE IF NOT EXISTS admin_orders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,source_table VARCHAR(128),source_key VARCHAR(191),customer_name VARCHAR(190) NOT NULL DEFAULT '',phone VARCHAR(60) NOT NULL DEFAULT '',address TEXT,note TEXT,amount DECIMAL(12,2) NOT NULL DEFAULT 0,payment_method VARCHAR(20) NOT NULL DEFAULT 'cash',status VARCHAR(40) NOT NULL DEFAULT 'new',courier_id BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY source_ref(source_table,source_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");@$conn->query("ALTER TABLE admin_orders ADD COLUMN payment_method VARCHAR(20) NOT NULL DEFAULT 'cash'");
$phone='+998998305603';$st=$conn->prepare('SELECT id FROM couriers WHERE phone=? LIMIT 1');$st->bind_param('s',$phone);$st->execute();if(!$st->get_result()->fetch_assoc()){$name='Daler Lavash';$pin=password_hash('Lavash',PASSWORD_DEFAULT);$st=$conn->prepare('INSERT INTO couriers(name,phone,pin_hash) VALUES(?,?,?)');$st->bind_param('sss',$name,$phone,$pin);$st->execute();}
if($a==='login'){ $phone=preg_replace('/[^0-9+]/','',trim($_POST['phone']??''));$pin=(string)($_POST['pin']??'');$st=$conn->prepare('SELECT * FROM couriers WHERE phone=? LIMIT 1');$st->bind_param('s',$phone);$st->execute();$c=$st->get_result()->fetch_assoc();if(!$c||!$c['pin_hash']||!password_verify($pin,$c['pin_hash']))out(['ok'=>false,'message'=>'Telefon yoki PIN noto‘g‘ri'],401);$_SESSION['courier_id']=(int)$c['id'];$conn->query('UPDATE couriers SET status="online",last_seen=NOW() WHERE id='.(int)$c['id']);out(['ok'=>true]);}
$id=(int)($_SESSION['courier_id']??0);if(!$id)out(['ok'=>false,'message'=>'Kirish kerak'],401);$conn->query('UPDATE couriers SET status="online",last_seen=NOW() WHERE id='.$id);
if($a==='logout'){$conn->query('UPDATE couriers SET status="offline" WHERE id='.$id);$_SESSION=[];session_destroy();out(['ok'=>true]);}
if($a==='me'){$st=$conn->prepare('SELECT id,name,phone,status FROM couriers WHERE id=?');$st->bind_param('i',$id);$st->execute();out(['ok'=>true,'data'=>$st->get_result()->fetch_assoc()]);}
if($a==='orders'){$st=$conn->prepare("SELECT * FROM admin_orders WHERE courier_id=? AND status IN('confirmed','preparing','delivering') ORDER BY created_at DESC");$st->bind_param('i',$id);$st->execute();$r=[];$q=$st->get_result();while($x=$q->fetch_assoc())$r[]=$x;out(['ok'=>true,'data'=>$r]);}
if($a==='status'){$oid=(int)($_POST['order_id']??0);$s=(string)($_POST['status']??'delivering');$allow=['preparing','delivering','completed'];if(!in_array($s,$allow,true))out(['ok'=>false],422);$st=$conn->prepare('UPDATE admin_orders SET status=? WHERE id=? AND courier_id=?');$st->bind_param('sii',$s,$oid,$id);$st->execute();out(['ok'=>true]);}
out(['ok'=>false,'message'=>'Unknown action'],404);}catch(Throwable $e){out(['ok'=>false,'message'=>'Server xatosi'],500);}
?>