<?php
ob_start();
ini_set('display_errors','0');
ini_set('log_errors','1');
error_reporting(E_ALL);
header('Content-Type: application/json; charset=utf-8');

const PANEL_USER = 'Daler';
const PANEL_PASS = 'Lavash';
const ADMIN_TOKEN = 'lavash_n1_admin_ultra_2026';
const COURIER_TOKEN = 'lavash_n1_courier_ultra_2026';
const COURIER_PHONE = '+998998305603';

function out($data, $code=200){
    while(ob_get_level()>0) ob_end_clean();
    http_response_code($code);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
    exit;
}
set_exception_handler(function(Throwable $e){ error_log('Panel API: '.$e->getMessage()); out(['ok'=>false,'message'=>'Server xatosi.'],500); });
register_shutdown_function(function(){ $e=error_get_last(); if($e && in_array($e['type'],[E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR],true)){ while(ob_get_level()>0) ob_end_clean(); http_response_code(500); header('Content-Type: application/json; charset=utf-8'); echo json_encode(['ok'=>false,'message'=>'Server xatosi.'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); } });
function db(){ static $loaded=false,$c=null; if($loaded)return $c; $loaded=true; @include __DIR__.'/conf.php'; if(isset($conn)&&$conn instanceof mysqli&&!$conn->connect_errno){$conn->set_charset('utf8mb4');return $conn;} return null; }
function businessStart(){ $d=strtotime(date('Y-m-d').' 06:00:00'); return date('Y-m-d H:i:s', time()>=$d?$d:strtotime('-1 day',$d)); }
function businessEnd(){ return date('Y-m-d H:i:s',strtotime(businessStart().' +18 hours')); }
function ensureSchema(mysqli $c){
    $c->query("CREATE TABLE IF NOT EXISTS admin_orders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,source_table VARCHAR(128) NULL,source_key VARCHAR(191) NULL,customer_name VARCHAR(190) NOT NULL DEFAULT '',phone VARCHAR(60) NOT NULL DEFAULT '',address TEXT NULL,note TEXT NULL,amount DECIMAL(12,2) NOT NULL DEFAULT 0,payment_method VARCHAR(20) NOT NULL DEFAULT 'cash',lat DECIMAL(10,7) NULL,lng DECIMAL(10,7) NULL,status VARCHAR(40) NOT NULL DEFAULT 'new',courier_id BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    foreach(["payment_method VARCHAR(20) NOT NULL DEFAULT 'cash'","lat DECIMAL(10,7) NULL","lng DECIMAL(10,7) NULL","courier_id BIGINT UNSIGNED NULL"] as $col){try{$c->query('ALTER TABLE admin_orders ADD COLUMN '.$col);}catch(Throwable $e){}}
    $c->query("CREATE TABLE IF NOT EXISTS couriers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,phone VARCHAR(60) NOT NULL UNIQUE,pin_hash VARCHAR(255) NULL,auth_token VARCHAR(128) NULL,status VARCHAR(30) NOT NULL DEFAULT 'offline',last_seen TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    foreach(["pin_hash VARCHAR(255) NULL","auth_token VARCHAR(128) NULL","status VARCHAR(30) NOT NULL DEFAULT 'offline'","last_seen TIMESTAMP NULL"] as $col){try{$c->query('ALTER TABLE couriers ADD COLUMN '.$col);}catch(Throwable $e){}}
    $c->query("CREATE TABLE IF NOT EXISTS customer_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NULL,name VARCHAR(190) NOT NULL,phone VARCHAR(60) NOT NULL UNIQUE,email VARCHAR(190) NULL,address TEXT NULL,password_hash VARCHAR(255) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $c->query("CREATE TABLE IF NOT EXISTS admin_settings(setting_key VARCHAR(80) PRIMARY KEY,setting_value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $c->query("INSERT IGNORE INTO admin_settings(setting_key,setting_value) VALUES('store_name','Lavash N1'),('phone','+998 99 830 56 03'),('address','Samarqand, Chelak 78-Maktab oldi'),('delivery_note','Tez va issiq dastavka'),('delivery_fee','0'),('promo_enabled','1'),('promo_title','Bugungi aksiya'),('promo_text','Lavash + kartoshka + ichimlik')");
}
function courierId(mysqli $c){ $p=COURIER_PHONE; $st=$c->prepare('SELECT id FROM couriers WHERE phone=? LIMIT 1'); $st->bind_param('s',$p);$st->execute();$r=$st->get_result()->fetch_assoc(); if($r)return (int)$r['id']; $h=password_hash(PANEL_PASS,PASSWORD_DEFAULT);$n='Daler Lavash';$t=COURIER_TOKEN;$st=$c->prepare("INSERT INTO couriers(name,phone,pin_hash,auth_token,status) VALUES(?,?,?,?, 'offline')");$st->bind_param('ssss',$n,$p,$h,$t);$st->execute();return (int)$c->insert_id; }
$action=(string)($_REQUEST['action']??'');
try{
    if($action==='health'){ $c=db(); out(['ok'=>true,'server'=>true,'database'=>(bool)$c,'business_start'=>businessStart(),'business_end'=>businessEnd(),'time'=>date('c')]); }
    if($action==='admin_login'){ $u=trim((string)($_POST['username']??''));$p=(string)($_POST['password']??''); if($u!==PANEL_USER||$p!==PANEL_PASS)out(['ok'=>false,'message'=>'Login yoki parol noto‘g‘ri.'],401); out(['ok'=>true,'token'=>ADMIN_TOKEN,'data'=>['name'=>'Daler']]); }
    if($action==='courier_login'){ $u=trim((string)($_POST['login']??''));$p=(string)($_POST['password']??''); if($u!==PANEL_USER||$p!==PANEL_PASS)out(['ok'=>false,'message'=>'Login yoki parol noto‘g‘ri.'],401); $c=db();$id=0;if($c){ensureSchema($c);$id=courierId($c);if($id){$st=$c->prepare("UPDATE couriers SET auth_token=?,status='online',last_seen=NOW() WHERE id=?");$t=COURIER_TOKEN;$st->bind_param('si',$t,$id);$st->execute();}} out(['ok'=>true,'token'=>COURIER_TOKEN,'data'=>['id'=>$id,'name'=>'Daler Lavash','phone'=>COURIER_PHONE]]); }
    $token=(string)($_REQUEST['token']??($_SERVER['HTTP_X_PANEL_TOKEN']??$_SERVER['HTTP_X_COURIER_TOKEN']??''));
    $isAdmin=hash_equals(ADMIN_TOKEN,$token);$isCourier=hash_equals(COURIER_TOKEN,$token);
    if($action==='admin_me'){if(!$isAdmin)out(['ok'=>false,'message'=>'Kirish kerak.'],401);out(['ok'=>true,'data'=>['name'=>'Daler','role'=>'admin']]);}
    if($action==='courier_me'){if(!$isCourier)out(['ok'=>false,'message'=>'Kirish kerak.'],401);$c=db();if(!$c)out(['ok'=>true,'data'=>['name'=>'Daler Lavash','phone'=>COURIER_PHONE,'status'=>'online']]);ensureSchema($c);$id=courierId($c);$st=$c->prepare("UPDATE couriers SET status='online',last_seen=NOW(),auth_token=? WHERE id=?");$t=COURIER_TOKEN;$st->bind_param('si',$t,$id);$st->execute();$st=$c->prepare('SELECT id,name,phone,status,last_seen FROM couriers WHERE id=? LIMIT 1');$st->bind_param('i',$id);$st->execute();out(['ok'=>true,'data'=>$st->get_result()->fetch_assoc()]);}
    if(!$isAdmin && !$isCourier) out(['ok'=>false,'message'=>'Kirish kerak.'],401);
    $c=db();if(!$c)out(['ok'=>false,'message'=>'Database bilan ulanishda muammo.'],503);ensureSchema($c);
    if($isAdmin){
        if($action==='summary'){$a=businessStart();$b=businessEnd();$st=$c->prepare("SELECT COUNT(*) orders,COALESCE(SUM(CASE WHEN status<>'cancelled' THEN amount ELSE 0 END),0) sales,COALESCE(SUM(CASE WHEN status='completed' THEN amount ELSE 0 END),0) completed_sales,COUNT(CASE WHEN status='new' THEN 1 END) new_count,COUNT(CASE WHEN status='delivering' THEN 1 END) delivering_count FROM admin_orders WHERE created_at>=? AND created_at<?");$st->bind_param('ss',$a,$b);$st->execute();$r=$st->get_result()->fetch_assoc();$online=(int)$c->query("SELECT COUNT(*) c FROM couriers WHERE status='online' AND last_seen>=NOW()-INTERVAL 2 MINUTE")->fetch_assoc()['c'];$all=(int)$c->query('SELECT COUNT(*) c FROM admin_orders')->fetch_assoc()['c'];out(['ok'=>true,'data'=>['orders'=>(int)$r['orders'],'sales'=>(float)$r['sales'],'completed_sales'=>(float)$r['completed_sales'],'new_count'=>(int)$r['new_count'],'delivering_count'=>(int)$r['delivering_count'],'online_couriers'=>$online,'history_total'=>$all,'business_start'=>$a,'business_end'=>$b]]);}
        if($action==='orders'||$action==='history'){ $limit=$action==='history'?1000:300;$status=trim((string)($_GET['status']??''));$where=$status!==''?' WHERE o.status=?':' WHERE 1=1';$sql="SELECT o.*,c.name courier_name,c.phone courier_phone FROM admin_orders o LEFT JOIN couriers c ON c.id=o.courier_id$where ORDER BY o.created_at DESC LIMIT $limit";$st=$c->prepare($sql);if($status!=='')$st->bind_param('s',$status);$st->execute();$q=$st->get_result();$rows=[];while($x=$q->fetch_assoc())$rows[]=$x;out(['ok'=>true,'data'=>$rows]);}
        if($action==='status'){$id=(int)($_POST['id']??0);$s=(string)($_POST['status']??'new');$allowed=['new','confirmed','preparing','delivering','completed','cancelled'];if(!$id||!in_array($s,$allowed,true))out(['ok'=>false,'message'=>'Status noto‘g‘ri.'],422);$cid=0;if($s==='delivering'){ $r=$c->query("SELECT id FROM couriers WHERE status='online' AND last_seen>=NOW()-INTERVAL 2 MINUTE ORDER BY last_seen DESC LIMIT 1");if($r&&($x=$r->fetch_assoc()))$cid=(int)$x['id']; }if($cid){$st=$c->prepare('UPDATE admin_orders SET status=?,courier_id=? WHERE id=?');$st->bind_param('sii',$s,$cid,$id);}else{$st=$c->prepare('UPDATE admin_orders SET status=? WHERE id=?');$st->bind_param('si',$s,$id);} $st->execute();out(['ok'=>true,'courier_id'=>$cid]);}
        if($action==='assign'){$oid=(int)($_POST['order_id']??0);$cid=(int)($_POST['courier_id']??0);$st=$c->prepare('UPDATE admin_orders SET courier_id=?,status=IF(status="new","confirmed",status) WHERE id=?');$st->bind_param('ii',$cid,$oid);$st->execute();out(['ok'=>true]);}
        if($action==='products'){$q=$c->query('SELECT * FROM product ORDER BY id DESC');$rows=[];while($x=$q->fetch_assoc())$rows[]=$x;out(['ok'=>true,'data'=>$rows]);}
        if($action==='product_save'){$id=(int)($_POST['id']??0);$title=trim((string)($_POST['p_title']??''));$price=(float)($_POST['p_prize']??0);$desc=trim((string)($_POST['p_desc']??''));$img=trim((string)($_POST['p_image']??'dish-1.png'));$cat=trim((string)($_POST['cat_id']??'cat-20001'));$subcat=trim((string)($_POST['scat_id']??'scat-30001'));$sub=trim((string)($_POST['p_subtitle']??''));$status=in_array($_POST['status']??'show',['show','hide'],true)?$_POST['status']:'show';if($title===''||$price<0)out(['ok'=>false,'message'=>'Nom va narxni to‘g‘ri kiriting.'],422);if($id){$st=$c->prepare('UPDATE product SET p_title=?,p_subtitle=?,p_desc=?,p_prize=?,cat_id=?,scat_id=?,p_image=?,status=? WHERE id=?');$st->bind_param('sssdssssi',$title,$sub,$desc,$price,$cat,$subcat,$img,$status,$id);}else{$pid='p-'.random_int(10000,99999);$uid=PANEL_USER;$date=date('Y-m-d H:i:s');$st=$c->prepare("INSERT INTO product(p_id,cat_id,scat_id,u_id,p_title,p_subtitle,p_desc,p_prize,p_image,status,action,date) VALUES(?,?,?,?,?,?,?,?,?,'show','far',?)");$st->bind_param('ssssssdsss',$pid,$cat,$subcat,$uid,$title,$sub,$desc,$price,$img,$date);} $st->execute();out(['ok'=>true]);}
        if($action==='product_delete'){$id=(int)($_POST['id']??0);$st=$c->prepare('DELETE FROM product WHERE id=?');$st->bind_param('i',$id);$st->execute();out(['ok'=>true]);}
        if($action==='couriers'){$q=$c->query('SELECT id,name,phone,status,last_seen FROM couriers ORDER BY id DESC');$rows=[];while($x=$q->fetch_assoc()){$x['online']=$x['status']==='online'&&strtotime($x['last_seen']??'')>=time()-120;$rows[]=$x;}out(['ok'=>true,'data'=>$rows]);}
        if($action==='courier_save'){$id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$phone=preg_replace('/[^0-9+]/','',trim((string)($_POST['phone']??'')));$pin=trim((string)($_POST['pin']??''));if($name===''||$phone==='')out(['ok'=>false,'message'=>'Ism va telefon kerak.'],422);if($id){if($pin!==''){$h=password_hash($pin,PASSWORD_DEFAULT);$st=$c->prepare('UPDATE couriers SET name=?,phone=?,pin_hash=? WHERE id=?');$st->bind_param('sssi',$name,$phone,$h,$id);}else{$st=$c->prepare('UPDATE couriers SET name=?,phone=? WHERE id=?');$st->bind_param('ssi',$name,$phone,$id);}}else{$h=password_hash($pin!==''?$pin:substr(preg_replace('/\D/','',$phone),-4),PASSWORD_DEFAULT);$st=$c->prepare("INSERT INTO couriers(name,phone,pin_hash,status) VALUES(?,?,?,'offline')");$st->bind_param('sss',$name,$phone,$h);} $st->execute();out(['ok'=>true]);}
        if($action==='courier_delete'){$id=(int)($_POST['id']??0);$st=$c->prepare('DELETE FROM couriers WHERE id=?');$st->bind_param('i',$id);$st->execute();out(['ok'=>true]);}
        if($action==='customers'){$q=$c->query("SELECT cp.*,COUNT(o.id) orders,COALESCE(SUM(CASE WHEN o.status<>'cancelled' THEN o.amount ELSE 0 END),0) spent FROM customer_profiles cp LEFT JOIN admin_orders o ON REPLACE(o.phone,' ','')=REPLACE(cp.phone,' ','') GROUP BY cp.id ORDER BY cp.id DESC");$rows=[];while($x=$q->fetch_assoc())$rows[]=$x;out(['ok'=>true,'data'=>$rows]);}
        if($action==='settings'){if($_SERVER['REQUEST_METHOD']==='POST'){foreach(['store_name','phone','address','delivery_note','delivery_fee','promo_enabled','promo_title','promo_text'] as $k){if(isset($_POST[$k])){$v=trim((string)$_POST[$k]);$st=$c->prepare('INSERT INTO admin_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$st->bind_param('ss',$k,$v);$st->execute();}}}$q=$c->query('SELECT setting_key,setting_value FROM admin_settings');$d=[];while($x=$q->fetch_assoc())$d[$x['setting_key']]=$x['setting_value'];out(['ok'=>true,'data'=>$d]);}
    }
    if($isCourier){
        $cid=courierId($c);$st=$c->prepare("UPDATE couriers SET auth_token=?,status='online',last_seen=NOW() WHERE id=?");$t=COURIER_TOKEN;$st->bind_param('si',$t,$cid);$st->execute();
        if($action==='courier_summary'){$a=businessStart();$b=businessEnd();$st=$c->prepare("SELECT COUNT(*) orders,COUNT(CASE WHEN status='completed' THEN 1 END) completed,COALESCE(SUM(CASE WHEN status='completed' THEN amount ELSE 0 END),0) sales FROM admin_orders WHERE courier_id=? AND created_at>=? AND created_at<?");$st->bind_param('iss',$cid,$a,$b);$st->execute();$r=$st->get_result()->fetch_assoc();out(['ok'=>true,'data'=>['orders'=>(int)$r['orders'],'completed'=>(int)$r['completed'],'sales'=>(float)$r['sales'],'business_start'=>$a,'business_end'=>$b]]);}
        if($action==='courier_orders'){$st=$c->prepare("SELECT id,customer_name,phone,address,note,amount,payment_method,lat,lng,status,created_at,updated_at FROM admin_orders WHERE courier_id=? AND status IN('confirmed','preparing','delivering') ORDER BY created_at DESC LIMIT 100");$st->bind_param('i',$cid);$st->execute();$q=$st->get_result();$rows=[];while($x=$q->fetch_assoc())$rows[]=$x;out(['ok'=>true,'data'=>$rows]);}
        if($action==='courier_history'){$st=$c->prepare('SELECT id,customer_name,phone,address,amount,payment_method,status,created_at,lat,lng FROM admin_orders WHERE courier_id=? ORDER BY created_at DESC LIMIT 500');$st->bind_param('i',$cid);$st->execute();$q=$st->get_result();$rows=[];while($x=$q->fetch_assoc())$rows[]=$x;out(['ok'=>true,'data'=>$rows]);}
        if($action==='courier_status'){$oid=(int)($_POST['order_id']??0);$s=(string)($_POST['status']??'');if(!$oid||!in_array($s,['preparing','delivering','completed'],true))out(['ok'=>false,'message'=>'Status noto‘g‘ri.'],422);$st=$c->prepare('UPDATE admin_orders SET status=? WHERE id=? AND courier_id=?');$st->bind_param('sii',$s,$oid,$cid);$st->execute();out(['ok'=>true]);}
    }
    out(['ok'=>false,'message'=>'Noma’lum amal.'],404);
}catch(Throwable $e){out(['ok'=>false,'message'=>'Server xatosi.'],500);}
